name: Release - Build and Publish Reports

on:
  release:
    types: [released]
#  workflow_dispatch:
#  push:
#    branches:
#      - "**"
#  pull_request:
#    branches:
#      - "**"

permissions:
  contents: write
  actions: write       # Necessary to cancel workflow executions
  checks: write        # Necessary to write reports
  pull-requests: write # Necessary to comment on PRs

jobs:
  build:
    name: Build, Test, and Attach Reports
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23
          cache: 'maven'

      - name: Build, test, and generate reports
        run: |
          mvn clean verify jacoco:report javadoc:javadoc --file pom.xml

      - name: Check if tests passed
        if: ${{ failure() }}
        run: |
          echo "Tests failed, stopping release process."
          exit 1

      - name: Generate report archive
        run: |
          mkdir release-report
          cp -r target/site/jacoco release-report/jacoco
          cp -r target/reports/apidocs release-report/javadoc
          cp -r target/surefire-reports release-report/test-reports
          zip -r release-report.zip release-report

      - name: Upload report as GitHub release asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          files: release-report.zip
